// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: authz/v1/authz.proto

// AuthzService 是 gitdash 的授权面（control plane）。
//
// 它把当前 SSH 服务在进程内直接调用的鉴权逻辑，收敛成一组稳定的一元 RPC，
// 供独立的 SSH 网关（后续拆分）通过 gRPC 调用。本服务只做「决策」，不碰仓库数据。
//
// 当前进程内 SSH 实现（internal/sshserver）的调用与 RPC 的对应关系：
//   - PublicKeyCallback: st.PublicKeys() 全表比对 + st.IsUserBanned  -> AuthorizePublicKey
//   - handleConn:        st.IsIPBanned                               -> IsIPBanned
//   - runGit:            st.CanWrite / st.CanRead                    -> CanWrite / CanRead

package authzv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthzService_AuthorizePublicKey_FullMethodName = "/gitdash.authz.v1.AuthzService/AuthorizePublicKey"
	AuthzService_IsIPBanned_FullMethodName         = "/gitdash.authz.v1.AuthzService/IsIPBanned"
	AuthzService_CanRead_FullMethodName            = "/gitdash.authz.v1.AuthzService/CanRead"
	AuthzService_CanWrite_FullMethodName           = "/gitdash.authz.v1.AuthzService/CanWrite"
	AuthzService_BranchProtection_FullMethodName   = "/gitdash.authz.v1.AuthzService/BranchProtection"
)

// AuthzServiceClient is the client API for AuthzService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthzService 授权决策服务。
type AuthzServiceClient interface {
	// AuthorizePublicKey 比对 SSH 公钥并返回其所属用户。
	// 比对在服务端完成（不回传任何公钥列表），语义与 sshserver.PublicKeyCallback 完全一致：
	// 命中后若账号被封禁则拒绝；未命中返回 authorized=false（reason=unknown public key）。
	AuthorizePublicKey(ctx context.Context, in *AuthorizePublicKeyRequest, opts ...grpc.CallOption) (*AuthorizePublicKeyResponse, error)
	// IsIPBanned 报告来源 IP 是否命中管理员黑名单（IP/CIDR）。
	IsIPBanned(ctx context.Context, in *IsIPBannedRequest, opts ...grpc.CallOption) (*IsIPBannedResponse, error)
	// CanRead 报告用户对仓库是否有读权限（clone/fetch/archive）。
	// 语义等价于 store.CanRead（已包含仓库封禁判断）。
	CanRead(ctx context.Context, in *CanReadRequest, opts ...grpc.CallOption) (*CanReadResponse, error)
	// CanWrite 报告用户对仓库是否有写权限（push）。
	// 语义等价于 store.CanWrite（已包含仓库封禁判断）。
	CanWrite(ctx context.Context, in *CanWriteRequest, opts ...grpc.CallOption) (*CanWriteResponse, error)
	// BranchProtection 返回指定分支的保护规则，供独立 SSH 机上的 pre-receive
	// hook 校验 push（避免分机部署时仍需访问数据库）。无规则时 protected=false。
	BranchProtection(ctx context.Context, in *BranchProtectionRequest, opts ...grpc.CallOption) (*BranchProtectionResponse, error)
}

type authzServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthzServiceClient(cc grpc.ClientConnInterface) AuthzServiceClient {
	return &authzServiceClient{cc}
}

func (c *authzServiceClient) AuthorizePublicKey(ctx context.Context, in *AuthorizePublicKeyRequest, opts ...grpc.CallOption) (*AuthorizePublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizePublicKeyResponse)
	err := c.cc.Invoke(ctx, AuthzService_AuthorizePublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzServiceClient) IsIPBanned(ctx context.Context, in *IsIPBannedRequest, opts ...grpc.CallOption) (*IsIPBannedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsIPBannedResponse)
	err := c.cc.Invoke(ctx, AuthzService_IsIPBanned_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzServiceClient) CanRead(ctx context.Context, in *CanReadRequest, opts ...grpc.CallOption) (*CanReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CanReadResponse)
	err := c.cc.Invoke(ctx, AuthzService_CanRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzServiceClient) CanWrite(ctx context.Context, in *CanWriteRequest, opts ...grpc.CallOption) (*CanWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CanWriteResponse)
	err := c.cc.Invoke(ctx, AuthzService_CanWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authzServiceClient) BranchProtection(ctx context.Context, in *BranchProtectionRequest, opts ...grpc.CallOption) (*BranchProtectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BranchProtectionResponse)
	err := c.cc.Invoke(ctx, AuthzService_BranchProtection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthzServiceServer is the server API for AuthzService service.
// All implementations must embed UnimplementedAuthzServiceServer
// for forward compatibility.
//
// AuthzService 授权决策服务。
type AuthzServiceServer interface {
	// AuthorizePublicKey 比对 SSH 公钥并返回其所属用户。
	// 比对在服务端完成（不回传任何公钥列表），语义与 sshserver.PublicKeyCallback 完全一致：
	// 命中后若账号被封禁则拒绝；未命中返回 authorized=false（reason=unknown public key）。
	AuthorizePublicKey(context.Context, *AuthorizePublicKeyRequest) (*AuthorizePublicKeyResponse, error)
	// IsIPBanned 报告来源 IP 是否命中管理员黑名单（IP/CIDR）。
	IsIPBanned(context.Context, *IsIPBannedRequest) (*IsIPBannedResponse, error)
	// CanRead 报告用户对仓库是否有读权限（clone/fetch/archive）。
	// 语义等价于 store.CanRead（已包含仓库封禁判断）。
	CanRead(context.Context, *CanReadRequest) (*CanReadResponse, error)
	// CanWrite 报告用户对仓库是否有写权限（push）。
	// 语义等价于 store.CanWrite（已包含仓库封禁判断）。
	CanWrite(context.Context, *CanWriteRequest) (*CanWriteResponse, error)
	// BranchProtection 返回指定分支的保护规则，供独立 SSH 机上的 pre-receive
	// hook 校验 push（避免分机部署时仍需访问数据库）。无规则时 protected=false。
	BranchProtection(context.Context, *BranchProtectionRequest) (*BranchProtectionResponse, error)
	mustEmbedUnimplementedAuthzServiceServer()
}

// UnimplementedAuthzServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthzServiceServer struct{}

func (UnimplementedAuthzServiceServer) AuthorizePublicKey(context.Context, *AuthorizePublicKeyRequest) (*AuthorizePublicKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthorizePublicKey not implemented")
}
func (UnimplementedAuthzServiceServer) IsIPBanned(context.Context, *IsIPBannedRequest) (*IsIPBannedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsIPBanned not implemented")
}
func (UnimplementedAuthzServiceServer) CanRead(context.Context, *CanReadRequest) (*CanReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CanRead not implemented")
}
func (UnimplementedAuthzServiceServer) CanWrite(context.Context, *CanWriteRequest) (*CanWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CanWrite not implemented")
}
func (UnimplementedAuthzServiceServer) BranchProtection(context.Context, *BranchProtectionRequest) (*BranchProtectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BranchProtection not implemented")
}
func (UnimplementedAuthzServiceServer) mustEmbedUnimplementedAuthzServiceServer() {}
func (UnimplementedAuthzServiceServer) testEmbeddedByValue()                      {}

// UnsafeAuthzServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthzServiceServer will
// result in compilation errors.
type UnsafeAuthzServiceServer interface {
	mustEmbedUnimplementedAuthzServiceServer()
}

func RegisterAuthzServiceServer(s grpc.ServiceRegistrar, srv AuthzServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthzServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthzService_ServiceDesc, srv)
}

func _AuthzService_AuthorizePublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizePublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).AuthorizePublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzService_AuthorizePublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).AuthorizePublicKey(ctx, req.(*AuthorizePublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzService_IsIPBanned_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsIPBannedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).IsIPBanned(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzService_IsIPBanned_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).IsIPBanned(ctx, req.(*IsIPBannedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzService_CanRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).CanRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzService_CanRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).CanRead(ctx, req.(*CanReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzService_CanWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).CanWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzService_CanWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).CanWrite(ctx, req.(*CanWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthzService_BranchProtection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BranchProtectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthzServiceServer).BranchProtection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthzService_BranchProtection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthzServiceServer).BranchProtection(ctx, req.(*BranchProtectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthzService_ServiceDesc is the grpc.ServiceDesc for AuthzService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthzService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gitdash.authz.v1.AuthzService",
	HandlerType: (*AuthzServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthorizePublicKey",
			Handler:    _AuthzService_AuthorizePublicKey_Handler,
		},
		{
			MethodName: "IsIPBanned",
			Handler:    _AuthzService_IsIPBanned_Handler,
		},
		{
			MethodName: "CanRead",
			Handler:    _AuthzService_CanRead_Handler,
		},
		{
			MethodName: "CanWrite",
			Handler:    _AuthzService_CanWrite_Handler,
		},
		{
			MethodName: "BranchProtection",
			Handler:    _AuthzService_BranchProtection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authz/v1/authz.proto",
}
