// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: authz/v1/authz.proto

// AuthzService 是 gitdash 的授权面（control plane）。
//
// 它把当前 SSH 服务在进程内直接调用的鉴权逻辑，收敛成一组稳定的一元 RPC，
// 供独立的 SSH 网关（后续拆分）通过 gRPC 调用。本服务只做「决策」，不碰仓库数据。
//
// 当前进程内 SSH 实现（internal/sshserver）的调用与 RPC 的对应关系：
//   - PublicKeyCallback: st.PublicKeys() 全表比对 + st.IsUserBanned  -> AuthorizePublicKey
//   - handleConn:        st.IsIPBanned                               -> IsIPBanned
//   - runGit:            st.CanWrite / st.CanRead                    -> CanWrite / CanRead

package authzv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthorizePublicKeyRequest 待鉴权的 SSH 公钥。
type AuthorizePublicKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SSH 公钥类型，如 "ssh-ed25519"、"ssh-rsa"（对应 ssh.PublicKey.Type()）。
	KeyType string `protobuf:"bytes,1,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	// SSH wire 格式的公钥主体（对应 ssh.PublicKey.Marshal()）。
	KeyBlob       []byte `protobuf:"bytes,2,opt,name=key_blob,json=keyBlob,proto3" json:"key_blob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizePublicKeyRequest) Reset() {
	*x = AuthorizePublicKeyRequest{}
	mi := &file_authz_v1_authz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizePublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizePublicKeyRequest) ProtoMessage() {}

func (x *AuthorizePublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authz_v1_authz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizePublicKeyRequest.ProtoReflect.Descriptor instead.
func (*AuthorizePublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_authz_v1_authz_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizePublicKeyRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *AuthorizePublicKeyRequest) GetKeyBlob() []byte {
	if x != nil {
		return x.KeyBlob
	}
	return nil
}

// AuthorizePublicKeyResponse 公钥鉴权结果。
type AuthorizePublicKeyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否通过鉴权（命中公钥且账号未被封禁）。
	Authorized bool `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
	// 通过时为用户名的公钥所有者；未通过为空。
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// 拒绝原因，便于日志与排查：如 "unknown public key"、"account is banned"。
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizePublicKeyResponse) Reset() {
	*x = AuthorizePublicKeyResponse{}
	mi := &file_authz_v1_authz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizePublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizePublicKeyResponse) ProtoMessage() {}

func (x *AuthorizePublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authz_v1_authz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizePublicKeyResponse.ProtoReflect.Descriptor instead.
func (*AuthorizePublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_authz_v1_authz_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizePublicKeyResponse) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

func (x *AuthorizePublicKeyResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthorizePublicKeyResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// IsIPBannedRequest 来源 IP 查询。
type IsIPBannedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 单个 IP（IPv4/IPv6）。
	Ip            string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsIPBannedRequest) Reset() {
	*x = IsIPBannedRequest{}
	mi := &file_authz_v1_authz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsIPBannedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsIPBannedRequest) ProtoMessage() {}

func (x *IsIPBannedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authz_v1_authz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsIPBannedRequest.ProtoReflect.Descriptor instead.
func (*IsIPBannedRequest) Descriptor() ([]byte, []int) {
	return file_authz_v1_authz_proto_rawDescGZIP(), []int{2}
}

func (x *IsIPBannedRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

// IsIPBannedResponse IP 黑名单查询结果。
type IsIPBannedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Banned        bool                   `protobuf:"varint,1,opt,name=banned,proto3" json:"banned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsIPBannedResponse) Reset() {
	*x = IsIPBannedResponse{}
	mi := &file_authz_v1_authz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsIPBannedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsIPBannedResponse) ProtoMessage() {}

func (x *IsIPBannedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authz_v1_authz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsIPBannedResponse.ProtoReflect.Descriptor instead.
func (*IsIPBannedResponse) Descriptor() ([]byte, []int) {
	return file_authz_v1_authz_proto_rawDescGZIP(), []int{3}
}

func (x *IsIPBannedResponse) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

// CanReadRequest 读权限查询。
type CanReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanReadRequest) Reset() {
	*x = CanReadRequest{}
	mi := &file_authz_v1_authz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanReadRequest) ProtoMessage() {}

func (x *CanReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authz_v1_authz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanReadRequest.ProtoReflect.Descriptor instead.
func (*CanReadRequest) Descriptor() ([]byte, []int) {
	return file_authz_v1_authz_proto_rawDescGZIP(), []int{4}
}

func (x *CanReadRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CanReadRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *CanReadRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// CanReadResponse 读权限结果。
type CanReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanReadResponse) Reset() {
	*x = CanReadResponse{}
	mi := &file_authz_v1_authz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanReadResponse) ProtoMessage() {}

func (x *CanReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authz_v1_authz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanReadResponse.ProtoReflect.Descriptor instead.
func (*CanReadResponse) Descriptor() ([]byte, []int) {
	return file_authz_v1_authz_proto_rawDescGZIP(), []int{5}
}

func (x *CanReadResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

// CanWriteRequest 写权限查询。
type CanWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanWriteRequest) Reset() {
	*x = CanWriteRequest{}
	mi := &file_authz_v1_authz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanWriteRequest) ProtoMessage() {}

func (x *CanWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authz_v1_authz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanWriteRequest.ProtoReflect.Descriptor instead.
func (*CanWriteRequest) Descriptor() ([]byte, []int) {
	return file_authz_v1_authz_proto_rawDescGZIP(), []int{6}
}

func (x *CanWriteRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *CanWriteRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *CanWriteRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// CanWriteResponse 写权限结果。
type CanWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanWriteResponse) Reset() {
	*x = CanWriteResponse{}
	mi := &file_authz_v1_authz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanWriteResponse) ProtoMessage() {}

func (x *CanWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authz_v1_authz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanWriteResponse.ProtoReflect.Descriptor instead.
func (*CanWriteResponse) Descriptor() ([]byte, []int) {
	return file_authz_v1_authz_proto_rawDescGZIP(), []int{7}
}

func (x *CanWriteResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

// BranchProtectionRequest 分支保护规则查询。
type BranchProtectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BranchProtectionRequest) Reset() {
	*x = BranchProtectionRequest{}
	mi := &file_authz_v1_authz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchProtectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchProtectionRequest) ProtoMessage() {}

func (x *BranchProtectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authz_v1_authz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchProtectionRequest.ProtoReflect.Descriptor instead.
func (*BranchProtectionRequest) Descriptor() ([]byte, []int) {
	return file_authz_v1_authz_proto_rawDescGZIP(), []int{8}
}

func (x *BranchProtectionRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *BranchProtectionRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *BranchProtectionRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

// BranchProtectionResponse 分支保护规则。
// protected=false 表示该分支无保护规则（调用方应放行）。
// 强推（force push）的祖先判断需本地仓库，由 hook 在拿到规则后自行完成。
type BranchProtectionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Protected      bool                   `protobuf:"varint,1,opt,name=protected,proto3" json:"protected,omitempty"`
	BlockDeletion  bool                   `protobuf:"varint,2,opt,name=block_deletion,json=blockDeletion,proto3" json:"block_deletion,omitempty"`
	BlockForcePush bool                   `protobuf:"varint,3,opt,name=block_force_push,json=blockForcePush,proto3" json:"block_force_push,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BranchProtectionResponse) Reset() {
	*x = BranchProtectionResponse{}
	mi := &file_authz_v1_authz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchProtectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchProtectionResponse) ProtoMessage() {}

func (x *BranchProtectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authz_v1_authz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchProtectionResponse.ProtoReflect.Descriptor instead.
func (*BranchProtectionResponse) Descriptor() ([]byte, []int) {
	return file_authz_v1_authz_proto_rawDescGZIP(), []int{9}
}

func (x *BranchProtectionResponse) GetProtected() bool {
	if x != nil {
		return x.Protected
	}
	return false
}

func (x *BranchProtectionResponse) GetBlockDeletion() bool {
	if x != nil {
		return x.BlockDeletion
	}
	return false
}

func (x *BranchProtectionResponse) GetBlockForcePush() bool {
	if x != nil {
		return x.BlockForcePush
	}
	return false
}

var File_authz_v1_authz_proto protoreflect.FileDescriptor

const file_authz_v1_authz_proto_rawDesc = "" +
	"\n" +
	"\x14authz/v1/authz.proto\x12\x10gitdash.authz.v1\"Q\n" +
	"\x19AuthorizePublicKeyRequest\x12\x19\n" +
	"\bkey_type\x18\x01 \x01(\tR\akeyType\x12\x19\n" +
	"\bkey_blob\x18\x02 \x01(\fR\akeyBlob\"p\n" +
	"\x1aAuthorizePublicKeyResponse\x12\x1e\n" +
	"\n" +
	"authorized\x18\x01 \x01(\bR\n" +
	"authorized\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"#\n" +
	"\x11IsIPBannedRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\",\n" +
	"\x12IsIPBannedResponse\x12\x16\n" +
	"\x06banned\x18\x01 \x01(\bR\x06banned\"V\n" +
	"\x0eCanReadRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"+\n" +
	"\x0fCanReadResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\"W\n" +
	"\x0fCanWriteRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\",\n" +
	"\x10CanWriteResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\"[\n" +
	"\x17BranchProtectionRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\"\x89\x01\n" +
	"\x18BranchProtectionResponse\x12\x1c\n" +
	"\tprotected\x18\x01 \x01(\bR\tprotected\x12%\n" +
	"\x0eblock_deletion\x18\x02 \x01(\bR\rblockDeletion\x12(\n" +
	"\x10block_force_push\x18\x03 \x01(\bR\x0eblockForcePush2\xe6\x03\n" +
	"\fAuthzService\x12o\n" +
	"\x12AuthorizePublicKey\x12+.gitdash.authz.v1.AuthorizePublicKeyRequest\x1a,.gitdash.authz.v1.AuthorizePublicKeyResponse\x12W\n" +
	"\n" +
	"IsIPBanned\x12#.gitdash.authz.v1.IsIPBannedRequest\x1a$.gitdash.authz.v1.IsIPBannedResponse\x12N\n" +
	"\aCanRead\x12 .gitdash.authz.v1.CanReadRequest\x1a!.gitdash.authz.v1.CanReadResponse\x12Q\n" +
	"\bCanWrite\x12!.gitdash.authz.v1.CanWriteRequest\x1a\".gitdash.authz.v1.CanWriteResponse\x12i\n" +
	"\x10BranchProtection\x12).gitdash.authz.v1.BranchProtectionRequest\x1a*.gitdash.authz.v1.BranchProtectionResponseB5Z3gitdash/backend/internal/grpcserver/authzv1;authzv1b\x06proto3"

var (
	file_authz_v1_authz_proto_rawDescOnce sync.Once
	file_authz_v1_authz_proto_rawDescData []byte
)

func file_authz_v1_authz_proto_rawDescGZIP() []byte {
	file_authz_v1_authz_proto_rawDescOnce.Do(func() {
		file_authz_v1_authz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authz_v1_authz_proto_rawDesc), len(file_authz_v1_authz_proto_rawDesc)))
	})
	return file_authz_v1_authz_proto_rawDescData
}

var file_authz_v1_authz_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_authz_v1_authz_proto_goTypes = []any{
	(*AuthorizePublicKeyRequest)(nil),  // 0: gitdash.authz.v1.AuthorizePublicKeyRequest
	(*AuthorizePublicKeyResponse)(nil), // 1: gitdash.authz.v1.AuthorizePublicKeyResponse
	(*IsIPBannedRequest)(nil),          // 2: gitdash.authz.v1.IsIPBannedRequest
	(*IsIPBannedResponse)(nil),         // 3: gitdash.authz.v1.IsIPBannedResponse
	(*CanReadRequest)(nil),             // 4: gitdash.authz.v1.CanReadRequest
	(*CanReadResponse)(nil),            // 5: gitdash.authz.v1.CanReadResponse
	(*CanWriteRequest)(nil),            // 6: gitdash.authz.v1.CanWriteRequest
	(*CanWriteResponse)(nil),           // 7: gitdash.authz.v1.CanWriteResponse
	(*BranchProtectionRequest)(nil),    // 8: gitdash.authz.v1.BranchProtectionRequest
	(*BranchProtectionResponse)(nil),   // 9: gitdash.authz.v1.BranchProtectionResponse
}
var file_authz_v1_authz_proto_depIdxs = []int32{
	0, // 0: gitdash.authz.v1.AuthzService.AuthorizePublicKey:input_type -> gitdash.authz.v1.AuthorizePublicKeyRequest
	2, // 1: gitdash.authz.v1.AuthzService.IsIPBanned:input_type -> gitdash.authz.v1.IsIPBannedRequest
	4, // 2: gitdash.authz.v1.AuthzService.CanRead:input_type -> gitdash.authz.v1.CanReadRequest
	6, // 3: gitdash.authz.v1.AuthzService.CanWrite:input_type -> gitdash.authz.v1.CanWriteRequest
	8, // 4: gitdash.authz.v1.AuthzService.BranchProtection:input_type -> gitdash.authz.v1.BranchProtectionRequest
	1, // 5: gitdash.authz.v1.AuthzService.AuthorizePublicKey:output_type -> gitdash.authz.v1.AuthorizePublicKeyResponse
	3, // 6: gitdash.authz.v1.AuthzService.IsIPBanned:output_type -> gitdash.authz.v1.IsIPBannedResponse
	5, // 7: gitdash.authz.v1.AuthzService.CanRead:output_type -> gitdash.authz.v1.CanReadResponse
	7, // 8: gitdash.authz.v1.AuthzService.CanWrite:output_type -> gitdash.authz.v1.CanWriteResponse
	9, // 9: gitdash.authz.v1.AuthzService.BranchProtection:output_type -> gitdash.authz.v1.BranchProtectionResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authz_v1_authz_proto_init() }
func file_authz_v1_authz_proto_init() {
	if File_authz_v1_authz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authz_v1_authz_proto_rawDesc), len(file_authz_v1_authz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authz_v1_authz_proto_goTypes,
		DependencyIndexes: file_authz_v1_authz_proto_depIdxs,
		MessageInfos:      file_authz_v1_authz_proto_msgTypes,
	}.Build()
	File_authz_v1_authz_proto = out.File
	file_authz_v1_authz_proto_goTypes = nil
	file_authz_v1_authz_proto_depIdxs = nil
}
